name: eubi-bridge
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy<2.0
  - scipy
  - h5py
  - imagecodecs
  - pip
  - pip:
    - "numpy<2.0"  # Constraint: don't upgrade numpy during pip install
    - "git+https://github.com/Euro-BioImaging/EuBI-Bridge.git@bf_bundled#egg=eubi_bridge[all]"
prefix: null  # Allow users to specify via -p flag or CONDA_PREFIX
